from abc import ABC, abstractmethod
from typing import Any
import datetime

class ApiService(ABC):
    def call_api(self, api_code, basetime) -> Any: ...
    def process_vileage_fcst(self, date: datetime.datetime, parameter, basetime: str) -> Any: ...
    def process_mid_fcst(self, date: datetime.datetime, parameter, basetime: str) -> Any: ...
    def process_living_wthr(self, date: datetime.datetime, parameter, basetime: str) -> Any: ...
    def process_arpltn(self, date: datetime.datetime, parameter) -> Any: ...
    def process_rise_set(self, date: datetime.datetime, parameter) -> Any: ...
    
class SchedulingService(ABC):
    # 해당 시간대에 실행할 동작
    @abstractmethod
    def scheduling_process(self, basetime: str) -> Any: ...